In [2]:
import numpy as np

In [7]:
e = np.array([5,3,2,6,8,4,1])
np.sort(e)

array([1, 2, 3, 4, 5, 6, 8])

In [8]:
g=np.array(['apple','banana','orange','mango','lichi'])
np.sort(g)

array(['apple', 'banana', 'lichi', 'mango', 'orange'], dtype='<U6')

In [10]:
np.random.randint(100)

49

In [11]:
np.random.rand(
    
)

0.8850956565006334

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a[2]

3

In [4]:
a[-1]

4

In [7]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[1:4]


array([2, 3, 4])

In [9]:
b[-1:4]

array([], dtype=int32)

In [10]:
b[:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
c=b.copy()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
d=b.view()
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a=np.array([1,2,3,4,5,6,7,8,,9,10,11,12])
b=a.reshape(4,3)
b  

SyntaxError: invalid syntax (772193100.py, line 1)

In [23]:
c=np.array([13,14,15])
d=np.concatenate((a,c))
d

array([ 1,  2,  3,  4, 13, 14, 15])

In [24]:
np.array_split(d,2)

[array([1, 2, 3, 4]), array([13, 14, 15])]

In [25]:
np.where(d==4)

(array([3], dtype=int64),)